site_name: Gebaeudedoc
site_description: Dokumentation und Nutzerhandbuch für die Gebaeudedoc Software
site_author: Paul Niemeier
theme:
  name: material
  language: de
  features:
    - navigation.sections
    - navigation.expand
    - toc.follow
    - content.code.copy
repo_url: https://github.com/paulniemeier/Gebaeudedoc
repo_name: GitHub
edit_uri: edit/main/docs/
nav:
  - Start: index.md
  - Installation: installation.md
  - Nutzung: usage.md
  - FAQ: faq.md
plugins:
  - search
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - tables
  - toc:
      permalink: true
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/paulniemeier/Gebaeudedoc
      name: Gebaeudedoc auf GitHub
